### ISSUE TITLE
Memory leaks on load

### ISSUE THREAD

**Issue by tosha-220** [oracle/graalpython#138]
I faced with some memory leaks when using python graal (Polyglot API).
I create test project to show leaks.

[https://github.com/tosha-220/python-graal](url)

I create one `Engine` and one `HostAccess` for whole application. `HostAccess` uses custom transformations from guest language objects to java objects.
Test project has endpoint to test js, endpoint to test python and endpoint to test both languages in one rest call.
My problem is when i send some requests (about 100 in 10 threads) to js endpoint i can see that 
no problems with memory occur, but in case of sending requests(100 in 10 threads) to python endpoint i see very big memory usage. Also after execution memory does not return to its original  state. So when application starts it consumes about 450mb, but after python test case it can be about 1.5 Gb or higher.

Application has js and python scripts with 3 functions described below. 
1) returns map from guest language to java
2) returns list from guest language to java
3) calls java object method from guest language and return result of calling.

All functions are performed on each rest call.

**Comment by msimacek** [comment]
We're doing a lot of caching in the AST to make the peak performance better, so a high memory usage is somewhat expected even though 1.5GB sounds like a bit too much.
@lukasstadler you were doing some measurements of memory usage recently, do you have any suggestions here?

Note that if you're concerned about memory usage in cloud/containers, then native image is the prefered way to do microservices like these. I think it already has spring boot support at this point.

Also note that comparison of python and javascript is not very fair. Javascript is a language with no module system. Python has a complex module import system (written in python) and has to load and execute parts of the standard library on startup due to that. Our startup performance and startup memory usage will be worse than javascript's due to that, at least on JVM. Native image could mitigate part of that by preloading things during build.

**Comment by msimacek** [comment]
We've fixed multiple memory leaks and added testing infrastructure for detecting them in the future. We also worked on reducing the memory usage in general. I believe this issue can be closed. Feel free to reopen if you disagree.
