### ISSUE TITLE
TypeError: multiple bases have instance lay-out conflict

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#211]
GraalPython is unable to capture this type error in the following piece of code:

```python
from collections import defaultdict, OrderedDict

class owndic(OrderedDict, defaultdict):
    pass
```

**CPython**

```python
python3 multiple_bases.py 
Traceback (most recent call last):
  File "multiple_bases.py", line 3, in <module>
    class owndic(OrderedDict, defaultdict):
TypeError: multiple bases have instance lay-out conflict
```

**GraalPython**
Wrongly passed.

**Comment by timfel** [comment]
It's not a type error for us. Why do you need it to be?

**Comment by timfel** [comment]
Or put a different way: that this is a type error on CPython is an arbitrary implementation detail. It happens because CPython implements these two classes in C in an incompatible way without there being any technical reason for that, it's just an artifact of the evolution of the code. We don't implement these types in C, and they are not incompatible for us.

**Comment by oroppas** [comment]
Ah. I see. Thanks for the clarification!
