### ISSUE TITLE
finally clause is not always executed

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#225]
I encountered one failure when running unit tests of [textfsm](https://github.com/google/textfsm)

```
graalpython -m pytest
========================================== test session starts ==========================================
platform linux -- Python 3.8.5, pytest-5.1.0, py-1.10.0, pluggy-0.13.1
rootdir: /u/cd4mcq/packages/graalvm/graalpython/textfsm/textfsm
collected 98 items                                                                                      

tests/clitable_test.py .................                                                          [ 17%]
tests/copyable_regex_object_test.py .                                                             [ 18%]
tests/terminal_test.py .........                                                                  [ 27%]
tests/textfsm_test.py .................................                                           [ 61%]
tests/texttable_test.py .......................F..............                                    [100%]

=============================================== FAILURES ================================================
```

The failing test is supposed to reset value in `finally` clause in
https://github.com/google/textfsm/blob/master/textfsm/texttable.py#L363-L365
but `graalpython` seems to fail to always call `finally` clause.

Here's how to replicate:

```
git clone https://github.com/google/textfsm
cd textfsm
graalpython ./setup.py build
graalpython -m pytest
```

**Comment by msimacek** [comment]
The problem there is not specific to GraalPython, you'd get the same failure with PyPy or Jython. It's not obvious, but the test relies on reference counting. I'll try to explain it on a simplified example, let's have a generator function like this:
```python
def mygen():
  try:
    yield 1
  finally:
    print("I'm done")
```
Now, let's instantiate the generator and get the value:
```
>>> g=mygen()
>>> next(g)
1
>>> 
```
Notice how the `finally` block didn't run yet, because the control in the generator didn't yet reach it. In order to do that, the generator has to be resumed again. Like this:
```
>>> next(g)
I'm done
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
```
But what happens if we never resumed it? In CPython, the generator gets resumed once again when it gets garbage collected. In the test, the loop that iterates the generator gets interrupted by an exception. In CPython, the generator's reference count drops to 0 because it's no longer referenced by the loop, the generator gets resumed and the `finally` block gets run. In implmenetations that don't use reference counting, the generator may get garbage collected (and thus resumed) at a later point or not at all. This is true for our implmentation, PyPy, Jython and probably more. Not having reference counting is a deliberate design choice that is very important for performance and most software doesn't rely on reference counting being present because it's discouraged even under CPython and is incompatible with PyPy and others. I'll need to close this issue, because we're not going to introduce reference counting.

If you care about the particular library, I advise you report to them that their tests fail on PyPy for this reason.

**Comment by oroppas** [comment]
@msimacek Thanks for the explanation!
