### ISSUE TITLE
No arm64 build

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [oracle/graalpython#259]
Heya, i was trying to install GraalPython from `gu` but there isn't any existing arm build, maybe it would be possible to build it for the future?

**Comment by kostya** [comment]
+1, I want to run this benchs https://github.com/kostya/jit-benchmarks on Apple M1. TruffleRuby and GraalNode, already works, but GraalPython missing.

**Comment by msimacek** [comment]
M1 support in GraalVM is being worked on, see https://github.com/oracle/graal/issues/2666. We cannot add M1 support to GraalPython before that is finished.

**Comment by lewurm** [comment]
The main blocker for GraalPython is that Sulong doesn’t work yet on darwin-aarch64 due to Apple decided to have a slightly different ABI than linux-aarch64. We need to implement this first. Specifically this affects functions using va_args. GraalPython depends quite a lot on Sulong for C extensions.

This won't happen for 22.1 I'm afraid.

Also a related: https://github.com/oracle/truffleruby/pull/2633

**Comment by Mythical-Forest-Collective** [comment]
> The main blocker for GraalPython is that Sulong doesn’t work yet on darwin-aarch64 due to Apple decided to have a slightly different ABI than linux-aarch64. We need to implement this first. Specifically this affects functions using va_args. GraalPython depends quite a lot on Sulong for C extensions.
> 
> This won't happen for 22.1 I'm afraid.
> 
> Also related: [oracle/truffleruby#2633](https://github.com/oracle/truffleruby/pull/2633)

Ah okay that makes sense. I was specifically talking about an arm64 build for linux but that makes sense

**Comment by msimacek** [comment]
Aarch64 builds should be available for the next release. You can get snapshot builds [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases/)
