### ISSUE TITLE
no python in component in GraalVM 22.3.2

### ISSUE THREAD

**Issue by The-Alchemist** [oracle/graalpython#336]
## How to Reproduce

Looks like 22.3.2 came out 2023-04-25, and I'd love to try out the new GraalPython, especially with the async support. 😀

### 22.3.2

```
> docker run --entrypoint bash --pull always -it ghcr.io/graalvm/graalvm-ce:22.3.2 gu install python                                          13:11:56
22.3.2: Pulling from graalvm/graalvm-ce
Digest: sha256:f02b4eba4a841d60e525e0b0a9db76eed3bb813fd39774ee089f9a888aea3751
Status: Image is up to date for ghcr.io/graalvm/graalvm-ce:22.3.2
Downloading: Component catalog from www.graalvm.org
Error: Component "python" is not available in catalog.
```

### 22.3.1

```
> docker run --entrypoint bash --pull always -it ghcr.io/graalvm/graalvm-ce:22.3.1 gu install python                                          12:38:37
22.3.1: Pulling from graalvm/graalvm-ce
Digest: sha256:6c937801101719e7d994f1eb534a9a91d315fe0494cabb664028cc4d9f8adbf5
Status: Image is up to date for ghcr.io/graalvm/graalvm-ce:22.3.1
Downloading: Component catalog from www.graalvm.org
Processing Component: GraalVM Python
Processing Component: LLVM.org toolchain
Processing Component: LLVM Runtime Core
Additional Components are required:
    LLVM.org toolchain (org.graalvm.llvm-toolchain, version 22.3.1), required by: GraalVM Python (org.graalvm.python)
    LLVM Runtime Core (org.graalvm.llvm, version 22.3.1), required by: GraalVM Python (org.graalvm.python)
Downloading: Component python: GraalVM Python from github.com
```

**Comment by msimacek** [comment]
Hi, releases that change the third version component (the z in x.y.z) are used only for backporting important bugfixes. Languages typically don't get any changes. There was no graalpy release in 22.3.2 at all, that's why you don't see it. Normally there is a feature release at the same time, which would be 23.0.0, but this time it got postponed to June 13 for some reason (see [release calendar](https://www.graalvm.org/release-notes/release-calendar/)). So async support will be available then. But you can always try the [latest snapshot](https://github.com/graalvm/graalvm-ce-dev-builds/releases/).

That being said, `gu` showing that there is no python available is a terrible user experience and our release engineering team is aware of it. But if they fix it, the python there will be identical to the one in 22.3.0, with no async support.

**Comment by The-Alchemist** [comment]
Thank you @msimacek !
