### ISSUE TITLE
scipy compilation speed is slow

### ISSUE THREAD

**Issue by ningpengtao-coder** [oracle/graalpython#388]
scipy v1.10.1 has a total of 1524 compilation units but compilation takes more than 10 minutes. May I ask what is the cause?

**Comment by msimacek** [comment]
It's due to how meson (their build system) invokes cython (code generation). They spawn a new cython process for each input file. Because GraalPy uses more memory per-process, we had to limit the number of parallel jobs to 4, or it would run out of memory on smaller systems. Meson doesn't have a separate job limit just for cython, so it also limits parallelism of the C compilations and everything else. Also GraalPy takes longer to start up a process, so the cython compilations are slower, but I think the lowered parallelism is a much bigger problem than this.

**Comment by msimacek** [comment]
I don't think there's anything we can do about this specifically. Meson won't change, running compilers this way is integral to their design. We're of course trying to lower our memory usage, but that's a difficult long term goal. Ideally, there would be prebuilt wheels for graalpy, so you wouldn't have to build scipy yourself at all.
